services:
  taskflow-db:
    container_name: taskflow-db
    image: mariadb:10.11
    user: "1000:1000"
    restart: always
    command: --port=3306 
    environment:
      MYSQL_ROOT_PASSWORD: # DB 루트 계정의 초기 비밀번호 설정
      MYSQL_DATABASE: # 초기 데이터베이스 이름 설정
      MYSQL_USER: # 애플리케이션에서 사용할 DB 사용자 계정 이름 설정
      MYSQL_PASSWORD: # 애플리케이션에서 사용할 DB 사용자 계정의 초기 비밀번호 설정
      TZ: Asia/Seoul
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - taskflow_network

  taskflow:
    container_name: taskflow
    image: taskflow:latest
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - taskflow-db
    volumes:
      - ./app:/app/app:rw
      - ./scripts:/app/scripts:rw
      - ./static:/app/static:rw
      - ./templates:/app/templates:rw
      - ./uploads:/app/uploads:rw
      - /data/monitoring/log/sys/day:/app/scripts/bash/result/sys/daily:rw
      - /data/monitoring/log/sys/once:/app/scripts/bash/result/sys/once:rw
      - /data/monitoring/log/tm/day:/app/scripts/bash/result/tm/daily:rw
      - /data/monitoring/log/tm/once:/app/scripts/bash/result/tm/once:rw
      - /etc/localtime:/etc/localtime:ro

    environment:
      - TZ=Asia/Seoul
      - ORACLE_CLIENT_MODE=thick
      - INSTALL_ORACLE_CLIENT=true
      - TB_HOME=/opt/tibero
      - TBCLI_WCHAR_TYPE=UCS2
      - ORACLE_SECRET_KEY=${ORACLE_SECRET_KEY}
      - ORACLE_DB_USER=${ORACLE_DB_USER}
      - ORACLE_DB_PASSWORD=${ORACLE_DB_PASSWORD}
      - ORACLE_DB_DSN=${ORACLE_DB_DSN}
      - TIBERO_SECRET_KEY=${TIBERO_SECRET_KEY}
      - TIBERO_DB_USER=${TIBERO_DB_USER}
      - TIBERO_DB_PASSWORD=${TIBERO_DB_PASSWORD}
      - TIBERO_DB_DSN=${TIBERO_DB_DSN}
      - MARIADB_SECRET_KEY=${MARIADB_SECRET_KEY}
      - DB_USER_ENC=${DB_USER_ENC}
      - DB_PASS_ENC=${DB_PASS_ENC}
      - DB_HOST_ENC=${DB_HOST_ENC}
      - DB_NAME_ENC=${DB_NAME_ENC}
      - DB_PORT=${DB_PORT}
    restart: always
    networks:
      - taskflow_network

networks:
  taskflow_network:
    driver: bridge