name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 
    
    steps:
      - name: 🚀 코드 최신화 및 서버 재시작
        run: |
          cd /home/tdadmin/techdata-fulltam-portal
          
          # 🌟 수정된 부분: 깃허브의 자체 임시 토큰을 사용하여 비밀번호 입력 없이 코드를 당겨옵니다.
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ndygeul/techdata-fulltam-portal.git main
          
          # 도커 빌드 및 실행
          docker compose up -d --build